export const EDITORIAL_EXPANSIONS: Record<string, { category: string; content: string }> = {
  "7 ways to decor your home like a professional": {
    "category": "Design",
    "content": "## Start with a room plan\n\nBefore buying anything, measure the room and draw its doors, windows and main walking routes. Decide what the room needs to do: host friends, provide a reading spot or accommodate evening television. Arrange your largest piece around that purpose. Leave enough space to move comfortably past it; a beautiful arrangement is not successful if you have to turn sideways to reach a chair.\n\n## Build a quiet foundation\n\nChoose a small palette from an existing rug, artwork or timber finish. Repeat those colors in different materials rather than buying a matching set. Linen, wood and woven surfaces can share a warm tone while adding distinct textures. Place the rug so the main seating feels connected, and use cushions to introduce a secondary color without overwhelming the foundation.\n\n## Finish with restraint\n\nGather smaller objects on a tray, vary their height and leave part of each surface empty. Check the room from the doorway and from a seated position: the view should have a focal point, not several competing displays. Live with your changes for a week before adding more. A room that works for your routines will feel more convincing than one assembled for a photograph."
  },
  "Inside a beautiful kitchen organization": {
    "category": "Kitchen",
    "content": "## Organize around the task\n\nStart with one everyday meal and notice every cupboard you open. Store preparation tools near the work surface, cooking utensils close to the hob and cups within easy reach of the kettle. Keep frequently used items in accessible drawers. Heavy equipment belongs low down, where lifting it does not require reaching overhead.\n\n## Give each shelf a clear purpose\n\nEmpty a single shelf at a time and group its contents before choosing containers. Measure the available depth and height, then use only as many organizers as the collection needs. Decanting is optional; visible labels and an easy-to-reach arrangement are often more useful than a row of beautiful jars. Retain cooking instructions and expiry information when transferring food.\n\n## Make the reset easy\n\nKeep a small space near the sink for drying and a clear surface for unpacking shopping. At the end of the day, return the few objects that belong on display and put the rest away. If an item repeatedly stays on the counter, reconsider where it is stored. Good organization reduces effort instead of adding another routine to maintain."
  },
  "Decor your bedroom for your children": {
    "category": "Bedroom",
    "content": "## Make room for changing interests\n\nChoose a calm base for walls and larger furniture, then give children a say in artwork, bedding and small accessories. These are easier to update than a whole room. Display drawings at their eye level and reserve a small area for their current collection, so the space feels personal without every surface becoming storage.\n\n## Separate rest from play\n\nA reading light and a reachable shelf can make the bedside feel settled. Use a rug or a low storage unit to define a play area away from the bed, keeping paths to the door clear. Think about where toys end up during real play rather than organizing only by how they look on a shelf.\n\n## Design for an easy tidy-up\n\nUse open bins for everyday toys and label them with words or pictures that children understand. Rotate less-used toys instead of keeping everything accessible at once. Follow the manufacturer's anchoring instructions for furniture, keep cords out of reach and check age suitability when choosing pieces. The aim is a comfortable room that supports daily routines and can grow with its owner."
  },
  "Modern home is beautiful and kid-friendly": {
    "category": "Living",
    "content": "## Choose fewer, more useful pieces\n\nA generous sofa, a practical table and accessible storage usually serve a family better than many small decorative items. Check the distance between furniture and doorways before purchasing. Rounded shapes can soften the look of a modern room, while a consistent wood finish helps practical pieces feel intentional rather than improvised.\n\n## Plan for everyday wear\n\nAsk how upholstery can be cleaned and whether covers can be removed before choosing a fabric. Consider the room's sunlight and daily traffic as well as its color palette. Place washable textiles where spills are likely, and keep a basket within reach for throws and toys. Durable does not have to mean hard or uncomfortable.\n\n## Let the room change through the day\n\nA small collection of toys can live in closed storage near the seating area, making the room easy to reset in the evening. Layer a reading lamp with softer background light instead of relying on one bright ceiling fixture. Make a place for the activities your household actually enjoys. A modern family home is most successful when its clean lines leave room for life, not when they demand constant tidying."
  },
  "Warm lighting changes everything": {
    "category": "Lighting",
    "content": "## Give each light a job\n\nAmbient light makes the room usable, task light helps with reading or working, and accent light draws attention to a particular surface or object. Start with the activity you struggle to see, then add a lamp that addresses it. A shade that hides the bulb from a seated position can make a reading corner more comfortable without lighting the entire room brightly.\n\n## Look at light after sunset\n\nTest lamps when daylight is no longer influencing the space. Notice reflections in screens, dark corners and bright bulbs visible from the sofa. Move a lamp a little before deciding that it needs a stronger bulb. Check the fixture's permitted bulb type and wattage, and use dimmable bulbs only with compatible controls.\n\n## Create an evening routine\n\nGroup lights by how you use the room: one setting for conversation, another for reading and a brighter setting for cleaning. Choose a consistent warm color temperature for living areas unless a specific task needs something different. You do not need to illuminate every corner. A few pools of light, placed around the people and objects you enjoy, often make a room feel more welcoming."
  },
  "Styling a cozy home corner": {
    "category": "Living",
    "content": "## Begin with the seat\n\nChoose a chair for the activity you want to enjoy, not just its silhouette. Sit back and check where your feet, arms and reading material naturally rest. Place a small table within easy reach for a cup or book, and leave a comfortable route around the arrangement. In a compact room, a visually light table can help the corner feel open.\n\n## Add light and a soft layer\n\nPosition a lamp to illuminate the page without shining directly into your eyes. A throw adds warmth, while a small rug can give the corner its own boundary. Repeat a color or material from elsewhere in the room so the new arrangement belongs to the whole space rather than looking like a separate display.\n\n## Keep the surface useful\n\nLimit the table to what supports the activity: a drink, a book and perhaps one decorative object. Store spare reading material in a basket rather than stacking it around the chair. Try using the corner at different times of day and adjust the lamp or table accordingly. The finishing touch is not another accessory; it is making the space easy enough to use every day."
  }
};
